server:
  port: 8001

spring:
  application:
    name: cloud-seata-order

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:33060/seata_order?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848,localhost:8849,localhost:8850
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
